server:
  port: 7777

spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    # ?? SMTP ?????
    host: smtp.qq.com
    # ?????????POP3/SMTP?????????????
    username: 953159409@qq.com
    # ??????????????????????????
    password: mhewafwljqllbddg
    # ?????
    nickname: 953159409
    # ???465?587?QQ?????????587?????
    port: 587
    # ????????UTF-8
    default-encoding: UTF-8
    # ???
    receivers: 1506319608@qq.com
    # ??SSL ????
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #???? DEBUG ???????????????????????????????
        debug: false